package Model;
// Generated Oct 20, 2018 11:23:12 AM by Hibernate Tools 4.3.1



/**
 * TblAccount generated by hbm2java
 */
public class TblAccount  implements java.io.Serializable {


     private int accountId;
     private Integer accountBalance;
     private String accountBeneficiary;
     private String accountType;

    public TblAccount() {
    }

	
    public TblAccount(int accountId) {
        this.accountId = accountId;
    }
    public TblAccount(int accountId, Integer accountBalance, String accountBeneficiary, String accountType) {
       this.accountId = accountId;
       this.accountBalance = accountBalance;
       this.accountBeneficiary = accountBeneficiary;
       this.accountType = accountType;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public Integer getAccountBalance() {
        return this.accountBalance;
    }
    
    public void setAccountBalance(Integer accountBalance) {
        this.accountBalance = accountBalance;
    }
    public String getAccountBeneficiary() {
        return this.accountBeneficiary;
    }
    
    public void setAccountBeneficiary(String accountBeneficiary) {
        this.accountBeneficiary = accountBeneficiary;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }




}


